version: '3.8'
services:
  angular:
    build:
      context: ./dear-doc-FE
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - nestjs

  nestjs:
    build:
      context: ./dear-doc-be
      dockerfile: Dockerfile
    ports:
      - "3000:3000"